# Generated by extendr: Do not edit by hand
# nolint start

#' @usage NULL
#' @useDynLib yr, .registration = TRUE
NULL

Transaction <- new.env(parent = emptyenv())

Transaction$lock <- function(doc, mutable = FALSE, origin = NULL) .Call(wrap__Transaction__lock, doc, mutable, origin)

Transaction$is_mutable_ec <- function() .Call(wrap__Transaction__is_mutable_ec, self)

Transaction$origin_ec <- function() .Call(wrap__Transaction__origin_ec, self)

Transaction$commit_ec <- function() .Call(wrap__Transaction__commit_ec, self)

Transaction$unlock <- function() .Call(wrap__Transaction__unlock, self)

Transaction$state_vector_ec <- function() .Call(wrap__Transaction__state_vector_ec, self)

Transaction$encode_diff_v1_ec <- function(state_vector) .Call(wrap__Transaction__encode_diff_v1_ec, self, state_vector)

Transaction$encode_diff_v2_ec <- function(state_vector) .Call(wrap__Transaction__encode_diff_v2_ec, self, state_vector)

Transaction$encode_state_as_update_v1_ec <- function(state_vector) .Call(wrap__Transaction__encode_state_as_update_v1_ec, self, state_vector)

Transaction$encode_state_as_update_v2_ec <- function(state_vector) .Call(wrap__Transaction__encode_state_as_update_v2_ec, self, state_vector)

Transaction$apply_update_v1_ec <- function(data) .Call(wrap__Transaction__apply_update_v1_ec, self, data)

Transaction$apply_update_v2_ec <- function(data) .Call(wrap__Transaction__apply_update_v2_ec, self, data)

Transaction$snapshot_ec <- function() .Call(wrap__Transaction__snapshot_ec, self)

#' @export
`$.Transaction` <- function (self, name) { func <- Transaction[[name]]; environment(func) <- environment(); func }

#' @export
`[[.Transaction` <- `$.Transaction`

Origin <- new.env(parent = emptyenv())

Origin$new_ec <- function(data) .Call(wrap__Origin__new_ec, data)

Origin$equal <- function(other) .Call(wrap__Origin__equal, self, other)

Origin$not_equal <- function(other) .Call(wrap__Origin__not_equal, self, other)

Origin$less_than <- function(other) .Call(wrap__Origin__less_than, self, other)

Origin$less_than_equal <- function(other) .Call(wrap__Origin__less_than_equal, self, other)

Origin$greater_than <- function(other) .Call(wrap__Origin__greater_than, self, other)

Origin$greater_than_equal <- function(other) .Call(wrap__Origin__greater_than_equal, self, other)

Origin$to_string <- function() .Call(wrap__Origin__to_string, self)

Origin$`__yr_print__` <- function() .Call(wrap__Origin____yr_print__, self)

Origin$to_bytes <- function() .Call(wrap__Origin__to_bytes, self)

Origin$to_hex <- function() .Call(wrap__Origin__to_hex, self)

#' @export
`$.Origin` <- function (self, name) { func <- Origin[[name]]; environment(func) <- environment(); func }

#' @export
`[[.Origin` <- `$.Origin`

Prelim <- new.env(parent = emptyenv())

Prelim$detect <- function(obj, recursive = FALSE) .Call(wrap__Prelim__detect, obj, recursive)

Prelim$text <- function(obj = "") .Call(wrap__Prelim__text, obj)

Prelim$array <- function(obj = NULL, recursive = FALSE) .Call(wrap__Prelim__array, obj, recursive)

Prelim$map <- function(obj = NULL, recursive = FALSE) .Call(wrap__Prelim__map, obj, recursive)

Prelim$any <- function(obj) .Call(wrap__Prelim__any, obj)

Prelim$inner <- function() .Call(wrap__Prelim__inner, self)

Prelim$is_text <- function() .Call(wrap__Prelim__is_text, self)

Prelim$is_array <- function() .Call(wrap__Prelim__is_array, self)

Prelim$is_map <- function() .Call(wrap__Prelim__is_map, self)

Prelim$is_any <- function() .Call(wrap__Prelim__is_any, self)

Prelim$is_recursive <- function() .Call(wrap__Prelim__is_recursive, self)

#' @export
`$.Prelim` <- function (self, name) { func <- Prelim[[name]]; environment(func) <- environment(); func }

#' @export
`[[.Prelim` <- `$.Prelim`

ArrayRef <- new.env(parent = emptyenv())

ArrayRef$len_ec <- function(transaction) .Call(wrap__ArrayRef__len_ec, self, transaction)

ArrayRef$insert_ec <- function(transaction, index, prelim) .Call(wrap__ArrayRef__insert_ec, self, transaction, index, prelim)

ArrayRef$insert_any_ec <- function(transaction, index, obj) .Call(wrap__ArrayRef__insert_any_ec, self, transaction, index, obj)

ArrayRef$insert_text_ec <- function(transaction, index) .Call(wrap__ArrayRef__insert_text_ec, self, transaction, index)

ArrayRef$insert_array_ec <- function(transaction, index) .Call(wrap__ArrayRef__insert_array_ec, self, transaction, index)

ArrayRef$insert_map_ec <- function(transaction, index) .Call(wrap__ArrayRef__insert_map_ec, self, transaction, index)

ArrayRef$get_ec <- function(transaction, index) .Call(wrap__ArrayRef__get_ec, self, transaction, index)

ArrayRef$remove_ec <- function(transaction, index) .Call(wrap__ArrayRef__remove_ec, self, transaction, index)

ArrayRef$observe_ec <- function(f, key) .Call(wrap__ArrayRef__observe_ec, self, f, key)

ArrayRef$unobserve_ec <- function(key) .Call(wrap__ArrayRef__unobserve_ec, self, key)

#' @export
`$.ArrayRef` <- function (self, name) { func <- ArrayRef[[name]]; environment(func) <- environment(); func }

#' @export
`[[.ArrayRef` <- `$.ArrayRef`

ArrayEvent <- new.env(parent = emptyenv())

ArrayEvent$target_ec <- function() .Call(wrap__ArrayEvent__target_ec, self)

ArrayEvent$delta_ec <- function(transaction) .Call(wrap__ArrayEvent__delta_ec, self, transaction)

ArrayEvent$path_ec <- function() .Call(wrap__ArrayEvent__path_ec, self)

ArrayEvent$inserts_ec <- function(transaction) .Call(wrap__ArrayEvent__inserts_ec, self, transaction)

ArrayEvent$removes_ec <- function(transaction) .Call(wrap__ArrayEvent__removes_ec, self, transaction)

#' @export
`$.ArrayEvent` <- function (self, name) { func <- ArrayEvent[[name]]; environment(func) <- environment(); func }

#' @export
`[[.ArrayEvent` <- `$.ArrayEvent`

MapRef <- new.env(parent = emptyenv())

MapRef$len_ec <- function(transaction) .Call(wrap__MapRef__len_ec, self, transaction)

MapRef$contains_key_ec <- function(transaction, key) .Call(wrap__MapRef__contains_key_ec, self, transaction, key)

MapRef$insert_ec <- function(transaction, key, prelim) .Call(wrap__MapRef__insert_ec, self, transaction, key, prelim)

MapRef$insert_any_ec <- function(transaction, key, obj) .Call(wrap__MapRef__insert_any_ec, self, transaction, key, obj)

MapRef$insert_text_ec <- function(transaction, key) .Call(wrap__MapRef__insert_text_ec, self, transaction, key)

MapRef$insert_array_ec <- function(transaction, key) .Call(wrap__MapRef__insert_array_ec, self, transaction, key)

MapRef$insert_map_ec <- function(transaction, key) .Call(wrap__MapRef__insert_map_ec, self, transaction, key)

MapRef$get_ec <- function(transaction, key) .Call(wrap__MapRef__get_ec, self, transaction, key)

MapRef$keys_ec <- function(transaction) .Call(wrap__MapRef__keys_ec, self, transaction)

MapRef$items_ec <- function(transaction) .Call(wrap__MapRef__items_ec, self, transaction)

MapRef$remove_ec <- function(transaction, key) .Call(wrap__MapRef__remove_ec, self, transaction, key)

MapRef$clear_ec <- function(transaction) .Call(wrap__MapRef__clear_ec, self, transaction)

MapRef$observe_ec <- function(f, key) .Call(wrap__MapRef__observe_ec, self, f, key)

MapRef$unobserve_ec <- function(key) .Call(wrap__MapRef__unobserve_ec, self, key)

#' @export
`$.MapRef` <- function (self, name) { func <- MapRef[[name]]; environment(func) <- environment(); func }

#' @export
`[[.MapRef` <- `$.MapRef`

MapEvent <- new.env(parent = emptyenv())

MapEvent$target_ec <- function() .Call(wrap__MapEvent__target_ec, self)

MapEvent$keys_ec <- function(transaction) .Call(wrap__MapEvent__keys_ec, self, transaction)

MapEvent$path_ec <- function() .Call(wrap__MapEvent__path_ec, self)

#' @export
`$.MapEvent` <- function (self, name) { func <- MapEvent[[name]]; environment(func) <- environment(); func }

#' @export
`[[.MapEvent` <- `$.MapEvent`

SyncMessage <- new.env(parent = emptyenv())

SyncMessage$decode_v1_ec <- function(data) .Call(wrap__SyncMessage__decode_v1_ec, data)

SyncMessage$decode_v2_ec <- function(data) .Call(wrap__SyncMessage__decode_v2_ec, data)

SyncMessage$from_sync_step1_ec <- function(state_vector) .Call(wrap__SyncMessage__from_sync_step1_ec, state_vector)

SyncMessage$from_sync_step2_ec <- function(data) .Call(wrap__SyncMessage__from_sync_step2_ec, data)

SyncMessage$from_update_ec <- function(data) .Call(wrap__SyncMessage__from_update_ec, data)

SyncMessage$equal <- function(other) .Call(wrap__SyncMessage__equal, self, other)

SyncMessage$not_equal <- function(other) .Call(wrap__SyncMessage__not_equal, self, other)

SyncMessage$encode_v1 <- function() .Call(wrap__SyncMessage__encode_v1, self)

SyncMessage$encode_v2 <- function() .Call(wrap__SyncMessage__encode_v2, self)

SyncMessage$step <- function() .Call(wrap__SyncMessage__step, self)

SyncMessage$is_sync_step1 <- function() .Call(wrap__SyncMessage__is_sync_step1, self)

SyncMessage$is_sync_step2 <- function() .Call(wrap__SyncMessage__is_sync_step2, self)

SyncMessage$is_update <- function() .Call(wrap__SyncMessage__is_update, self)

SyncMessage$state_vector_ec <- function() .Call(wrap__SyncMessage__state_vector_ec, self)

SyncMessage$data_ec <- function() .Call(wrap__SyncMessage__data_ec, self)

#' @export
`$.SyncMessage` <- function (self, name) { func <- SyncMessage[[name]]; environment(func) <- environment(); func }

#' @export
`[[.SyncMessage` <- `$.SyncMessage`

Message <- new.env(parent = emptyenv())

Message$decode_v1_ec <- function(data) .Call(wrap__Message__decode_v1_ec, data)

Message$decode_v2_ec <- function(data) .Call(wrap__Message__decode_v2_ec, data)

Message$new_ec <- function(obj) .Call(wrap__Message__new_ec, obj)

Message$inner <- function() .Call(wrap__Message__inner, self)

Message$is_sync_message <- function() .Call(wrap__Message__is_sync_message, self)

Message$encode_v1 <- function() .Call(wrap__Message__encode_v1, self)

Message$encode_v2 <- function() .Call(wrap__Message__encode_v2, self)

#' @export
`$.Message` <- function (self, name) { func <- Message[[name]]; environment(func) <- environment(); func }

#' @export
`[[.Message` <- `$.Message`

Unsupported <- new.env(parent = emptyenv())

Unsupported$new <- function() .Call(wrap__Unsupported__new)

#' @export
`$.Unsupported` <- function (self, name) { func <- Unsupported[[name]]; environment(func) <- environment(); func }

#' @export
`[[.Unsupported` <- `$.Unsupported`

StateVector <- new.env(parent = emptyenv())

StateVector$decode_v1_ec <- function(data) .Call(wrap__StateVector__decode_v1_ec, data)

StateVector$decode_v2_ec <- function(data) .Call(wrap__StateVector__decode_v2_ec, data)

StateVector$is_empty <- function() .Call(wrap__StateVector__is_empty, self)

StateVector$len <- function() .Call(wrap__StateVector__len, self)

StateVector$contains_client <- function(client_id) .Call(wrap__StateVector__contains_client, self, client_id)

StateVector$equal <- function(other) .Call(wrap__StateVector__equal, self, other)

StateVector$not_equal <- function(other) .Call(wrap__StateVector__not_equal, self, other)

StateVector$less_than <- function(other) .Call(wrap__StateVector__less_than, self, other)

StateVector$less_than_equal <- function(other) .Call(wrap__StateVector__less_than_equal, self, other)

StateVector$greater_than <- function(other) .Call(wrap__StateVector__greater_than, self, other)

StateVector$greater_than_equal <- function(other) .Call(wrap__StateVector__greater_than_equal, self, other)

StateVector$encode_v1 <- function() .Call(wrap__StateVector__encode_v1, self)

StateVector$encode_v2 <- function() .Call(wrap__StateVector__encode_v2, self)

#' @export
`$.StateVector` <- function (self, name) { func <- StateVector[[name]]; environment(func) <- environment(); func }

#' @export
`[[.StateVector` <- `$.StateVector`

DeleteSet <- new.env(parent = emptyenv())

DeleteSet$decode_v1_ec <- function(data) .Call(wrap__DeleteSet__decode_v1_ec, data)

DeleteSet$decode_v2_ec <- function(data) .Call(wrap__DeleteSet__decode_v2_ec, data)

DeleteSet$new <- function() .Call(wrap__DeleteSet__new)

DeleteSet$is_empty <- function() .Call(wrap__DeleteSet__is_empty, self)

DeleteSet$len <- function() .Call(wrap__DeleteSet__len, self)

DeleteSet$is_deleted_ec <- function(id) .Call(wrap__DeleteSet__is_deleted_ec, self, id)

DeleteSet$equal <- function(other) .Call(wrap__DeleteSet__equal, self, other)

DeleteSet$not_equal <- function(other) .Call(wrap__DeleteSet__not_equal, self, other)

DeleteSet$encode_v1 <- function() .Call(wrap__DeleteSet__encode_v1, self)

DeleteSet$encode_v2 <- function() .Call(wrap__DeleteSet__encode_v2, self)

DeleteSet$squash <- function() .Call(wrap__DeleteSet__squash, self)

DeleteSet$merge <- function(other) .Call(wrap__DeleteSet__merge, self, other)

#' @export
`$.DeleteSet` <- function (self, name) { func <- DeleteSet[[name]]; environment(func) <- environment(); func }

#' @export
`[[.DeleteSet` <- `$.DeleteSet`

Snapshot <- new.env(parent = emptyenv())

Snapshot$new <- function(state_map, delete_set) .Call(wrap__Snapshot__new, state_map, delete_set)

Snapshot$decode_v1_ec <- function(data) .Call(wrap__Snapshot__decode_v1_ec, data)

Snapshot$decode_v2_ec <- function(data) .Call(wrap__Snapshot__decode_v2_ec, data)

Snapshot$encode_v1 <- function() .Call(wrap__Snapshot__encode_v1, self)

Snapshot$encode_v2 <- function() .Call(wrap__Snapshot__encode_v2, self)

Snapshot$equal <- function(other) .Call(wrap__Snapshot__equal, self, other)

Snapshot$not_equal <- function(other) .Call(wrap__Snapshot__not_equal, self, other)

#' @export
`$.Snapshot` <- function (self, name) { func <- Snapshot[[name]]; environment(func) <- environment(); func }

#' @export
`[[.Snapshot` <- `$.Snapshot`

TextRef <- new.env(parent = emptyenv())

TextRef$len_ec <- function(transaction) .Call(wrap__TextRef__len_ec, self, transaction)

TextRef$insert_ec <- function(transaction, index, chunk) .Call(wrap__TextRef__insert_ec, self, transaction, index, chunk)

TextRef$push_ec <- function(transaction, chunk) .Call(wrap__TextRef__push_ec, self, transaction, chunk)

TextRef$remove_range_ec <- function(transaction, index, len) .Call(wrap__TextRef__remove_range_ec, self, transaction, index, len)

TextRef$get_string_ec <- function(transaction) .Call(wrap__TextRef__get_string_ec, self, transaction)

TextRef$observe_ec <- function(f, key) .Call(wrap__TextRef__observe_ec, self, f, key)

TextRef$unobserve_ec <- function(key) .Call(wrap__TextRef__unobserve_ec, self, key)

#' @export
`$.TextRef` <- function (self, name) { func <- TextRef[[name]]; environment(func) <- environment(); func }

#' @export
`[[.TextRef` <- `$.TextRef`

TextEvent <- new.env(parent = emptyenv())

TextEvent$target_ec <- function() .Call(wrap__TextEvent__target_ec, self)

TextEvent$delta_ec <- function(transaction) .Call(wrap__TextEvent__delta_ec, self, transaction)

TextEvent$path_ec <- function() .Call(wrap__TextEvent__path_ec, self)

#' @export
`$.TextEvent` <- function (self, name) { func <- TextEvent[[name]]; environment(func) <- environment(); func }

#' @export
`[[.TextEvent` <- `$.TextEvent`

Update <- new.env(parent = emptyenv())

Update$decode_v1_ec <- function(data) .Call(wrap__Update__decode_v1_ec, data)

Update$decode_v2_ec <- function(data) .Call(wrap__Update__decode_v2_ec, data)

Update$new <- function() .Call(wrap__Update__new)

Update$is_empty <- function() .Call(wrap__Update__is_empty, self)

Update$extends <- function(state_vector) .Call(wrap__Update__extends, self, state_vector)

Update$encode_v1 <- function() .Call(wrap__Update__encode_v1, self)

Update$encode_v2 <- function() .Call(wrap__Update__encode_v2, self)

Update$state_vector <- function() .Call(wrap__Update__state_vector, self)

Update$state_vector_lower <- function() .Call(wrap__Update__state_vector_lower, self)

Update$to_string <- function() .Call(wrap__Update__to_string, self)

Update$`__yr_print__` <- function() .Call(wrap__Update____yr_print__, self)

#' @export
`$.Update` <- function (self, name) { func <- Update[[name]]; environment(func) <- environment(); func }

#' @export
`[[.Update` <- `$.Update`

Doc <- new.env(parent = emptyenv())

Doc$new <- function() .Call(wrap__Doc__new)

Doc$client_id <- function() .Call(wrap__Doc__client_id, self)

Doc$guid <- function() .Call(wrap__Doc__guid, self)

Doc$get_or_insert_text <- function(name) .Call(wrap__Doc__get_or_insert_text, self, name)

Doc$get_or_insert_map <- function(name) .Call(wrap__Doc__get_or_insert_map, self, name)

Doc$get_or_insert_array <- function(name) .Call(wrap__Doc__get_or_insert_array, self, name)

Doc$to_string <- function() .Call(wrap__Doc__to_string, self)

Doc$`__yr_print__` <- function() .Call(wrap__Doc____yr_print__, self)

Doc$observe_transaction_cleanup_ec <- function(f, key) .Call(wrap__Doc__observe_transaction_cleanup_ec, self, f, key)

Doc$unobserve_transaction_cleanup_ec <- function(key) .Call(wrap__Doc__unobserve_transaction_cleanup_ec, self, key)

#' @export
`$.Doc` <- function (self, name) { func <- Doc[[name]]; environment(func) <- environment(); func }

#' @export
`[[.Doc` <- `$.Doc`

TransactionCleanupEvent <- new.env(parent = emptyenv())

TransactionCleanupEvent$before_state_ec <- function() .Call(wrap__TransactionCleanupEvent__before_state_ec, self)

TransactionCleanupEvent$after_state_ec <- function() .Call(wrap__TransactionCleanupEvent__after_state_ec, self)

TransactionCleanupEvent$delete_set_ec <- function() .Call(wrap__TransactionCleanupEvent__delete_set_ec, self)

#' @export
`$.TransactionCleanupEvent` <- function (self, name) { func <- TransactionCleanupEvent[[name]]; environment(func) <- environment(); func }

#' @export
`[[.TransactionCleanupEvent` <- `$.TransactionCleanupEvent`

# nolint end
