# Generated by extendr: Do not edit by hand
# nolint start

#' @usage NULL
#' @useDynLib yar, .registration = TRUE
NULL

Doc <- new.env(parent = emptyenv())

Doc$new <- function() .Call(wrap__Doc__new)

Doc$client_id <- function() .Call(wrap__Doc__client_id, self)

Doc$guid <- function() .Call(wrap__Doc__guid, self)

Doc$get_or_insert_text <- function(name) .Call(wrap__Doc__get_or_insert_text, self, name)

#' @export
`$.Doc` <- function (self, name) { func <- Doc[[name]]; environment(func) <- environment(); func }

#' @export
`[[.Doc` <- `$.Doc`

StateVector <- new.env(parent = emptyenv())

StateVector$decode_v1 <- function(data) .Call(wrap__StateVector__decode_v1, data)

StateVector$decode_v2 <- function(data) .Call(wrap__StateVector__decode_v2, data)

StateVector$is_empty <- function() .Call(wrap__StateVector__is_empty, self)

StateVector$len <- function() .Call(wrap__StateVector__len, self)

StateVector$contains_client <- function(client_id) .Call(wrap__StateVector__contains_client, self, client_id)

StateVector$encode_v1 <- function() .Call(wrap__StateVector__encode_v1, self)

StateVector$encode_v2 <- function() .Call(wrap__StateVector__encode_v2, self)

#' @export
`$.StateVector` <- function (self, name) { func <- StateVector[[name]]; environment(func) <- environment(); func }

#' @export
`[[.StateVector` <- `$.StateVector`

TextRef <- new.env(parent = emptyenv())

TextRef$len <- function(transaction) .Call(wrap__TextRef__len, self, transaction)

TextRef$insert <- function(transaction, index, chunk) .Call(wrap__TextRef__insert, self, transaction, index, chunk)

TextRef$push <- function(transaction, chunk) .Call(wrap__TextRef__push, self, transaction, chunk)

TextRef$remove_range <- function(transaction, index, len) .Call(wrap__TextRef__remove_range, self, transaction, index, len)

TextRef$get_string <- function(transaction) .Call(wrap__TextRef__get_string, self, transaction)

#' @export
`$.TextRef` <- function (self, name) { func <- TextRef[[name]]; environment(func) <- environment(); func }

#' @export
`[[.TextRef` <- `$.TextRef`

Transaction <- new.env(parent = emptyenv())

Transaction$new <- function(doc, mutable = FALSE) .Call(wrap__Transaction__new, doc, mutable)

Transaction$commit <- function() .Call(wrap__Transaction__commit, self)

Transaction$drop <- function() .Call(wrap__Transaction__drop, self)

Transaction$state_vector <- function() .Call(wrap__Transaction__state_vector, self)

Transaction$encode_diff_v1 <- function(state_vector) .Call(wrap__Transaction__encode_diff_v1, self, state_vector)

Transaction$encode_diff_v2 <- function(state_vector) .Call(wrap__Transaction__encode_diff_v2, self, state_vector)

Transaction$apply_update_v1 <- function(data) .Call(wrap__Transaction__apply_update_v1, self, data)

Transaction$apply_update_v2 <- function(data) .Call(wrap__Transaction__apply_update_v2, self, data)

#' @export
`$.Transaction` <- function (self, name) { func <- Transaction[[name]]; environment(func) <- environment(); func }

#' @export
`[[.Transaction` <- `$.Transaction`

Update <- new.env(parent = emptyenv())

Update$decode_v1 <- function(data) .Call(wrap__Update__decode_v1, data)

Update$decode_v2 <- function(data) .Call(wrap__Update__decode_v2, data)

Update$new <- function() .Call(wrap__Update__new)

Update$is_empty <- function() .Call(wrap__Update__is_empty, self)

Update$extends <- function(state_vector) .Call(wrap__Update__extends, self, state_vector)

Update$encode_v1 <- function() .Call(wrap__Update__encode_v1, self)

Update$encode_v2 <- function() .Call(wrap__Update__encode_v2, self)

Update$state_vector <- function() .Call(wrap__Update__state_vector, self)

Update$state_vector_lower <- function() .Call(wrap__Update__state_vector_lower, self)

#' @export
`$.Update` <- function (self, name) { func <- Update[[name]]; environment(func) <- environment(); func }

#' @export
`[[.Update` <- `$.Update`

# nolint end
